/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author M.K
 */
public class AllContacts extends javax.swing.JFrame {

    /**
     * Creates new form AllContacts
     */
    public AllContacts() {
        initComponents();
        btnExit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();
        btnView = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        lblHome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblViewContacts = new javax.swing.JTextArea();
        lblTitle = new javax.swing.JLabel();
        bg_walpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(600, 423));
        setMinimumSize(new java.awt.Dimension(600, 423));

        jPanel1.setLayout(null);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(540, 20, 40, 40);

        lblView.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        lblView.setForeground(new java.awt.Color(51, 51, 51));
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("View All Contact");
        jPanel1.add(lblView);
        lblView.setBounds(0, 390, 170, 30);

        btnView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-show-property-100.png"))); // NOI18N
        btnView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnViewMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnViewMouseReleased(evt);
            }
        });
        jPanel1.add(btnView);
        btnView.setBounds(0, 300, 100, 100);

        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(500, 300, 100, 100);

        lblHome.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        lblHome.setForeground(new java.awt.Color(51, 51, 51));
        lblHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHome.setText("Home");
        jPanel1.add(lblHome);
        lblHome.setBounds(500, 390, 100, 30);

        lblViewContacts.setBackground(new java.awt.Color(204, 204, 204));
        lblViewContacts.setColumns(20);
        lblViewContacts.setFont(new java.awt.Font("Arial Unicode MS", 0, 12)); // NOI18N
        lblViewContacts.setForeground(new java.awt.Color(0, 0, 0));
        lblViewContacts.setLineWrap(true);
        lblViewContacts.setRows(5);
        lblViewContacts.setToolTipText("");
        lblViewContacts.setBorder(null);
        lblViewContacts.setMaximumSize(new java.awt.Dimension(100, 15));
        jScrollPane1.setViewportView(lblViewContacts);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(140, 140, 350, 200);

        lblTitle.setFont(new java.awt.Font("Arial Unicode MS", 1, 25)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(0, 0, 0));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("All Contacts");
        lblTitle.setMaximumSize(new java.awt.Dimension(386, 34));
        lblTitle.setMinimumSize(new java.awt.Dimension(386, 34));
        lblTitle.setPreferredSize(new java.awt.Dimension(386, 34));
        jPanel1.add(lblTitle);
        lblTitle.setBounds(0, 30, 600, 50);

        bg_walpaper.setFont(new java.awt.Font("Arial Unicode MS", 0, 15)); // NOI18N
        bg_walpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/paper-1215551_1280.jpg"))); // NOI18N
        jPanel1.add(bg_walpaper);
        bg_walpaper.setBounds(0, 0, 600, 423);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48 (1).png")));
        
    }//GEN-LAST:event_btnExitMousePressed

    
    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
         btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png")));
        this.dispose();
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMousePressed
        // TODO add your handling code here:
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-show-property-100 (2).png")));
        
        String dbName = "jdbc:mysql://localhost/DBPhoneBook";
        String dbUser = "root";
        String dbPass = "root";
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;   
        try{
            String sql= "SELECT uName, uContact, uEmail FROM tab_Contact";
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection (dbName,dbUser,"");
            st = conn.createStatement();
            rs = st.executeQuery(sql);
  
            while(rs.next()){
                String uName = rs.getString("uName");
                String uContact = rs.getString("uContact");
                String uEmail = rs.getString("uEmail");
                lblViewContacts.setText(lblViewContacts.getText() +"Name:  "+ uName + "\n");
                System.out.print(uName + "\n");
                lblViewContacts.setText(lblViewContacts.getText() +"Contact:  "+ uContact + "\n");
                System.out.print(uContact + "\n");
                lblViewContacts.setText(lblViewContacts.getText() +"Email ID:  "+ uEmail + "\n\n");
                System.out.print(uEmail + "\n\n");
            }
            
         }
        catch(ClassNotFoundException | SQLException e){
            System.out.print(e);
}

        
    }//GEN-LAST:event_btnViewMousePressed

    private void btnViewMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseReleased
        // TODO add your handling code here:
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-show-property-100.png")));
    }//GEN-LAST:event_btnViewMouseReleased

    private void btnViewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseEntered
        // TODO add your handling code here:
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-show-property-100 (1).png")));
    }//GEN-LAST:event_btnViewMouseEntered

    private void btnViewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewMouseExited
        // TODO add your handling code here:
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-show-property-100.png")));
    }//GEN-LAST:event_btnViewMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (2).png")));
        
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
        new MainFram().setVisible(true);
        new AllContacts().setVisible(false);
    }//GEN-LAST:event_btnHomeMouseReleased

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (1).png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllContacts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllContacts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_walpaper;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnView;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblView;
    private javax.swing.JTextArea lblViewContacts;
    // End of variables declaration//GEN-END:variables
}
