/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author M.K
 */
public class DeleteContact extends javax.swing.JFrame {

    /**
     * Creates new form DeleteContact
     */
    public DeleteContact() {
        initComponents();
        btnExit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDelName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDelNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDeleteMessage = new javax.swing.JLabel();
        btnDeleteName = new javax.swing.JLabel();
        btnDeleteNumber = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bg_walpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 423));
        setMinimumSize(new java.awt.Dimension(600, 423));

        jPanel1.setLayout(null);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(540, 20, 40, 40);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete Contact");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 30, 600, 50);

        txtDelName.setBackground(new java.awt.Color(204, 255, 204));
        txtDelName.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        txtDelName.setForeground(new java.awt.Color(153, 153, 153));
        txtDelName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDelName.setText("Name");
        txtDelName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDelName.setMaximumSize(new java.awt.Dimension(4, 27));
        txtDelName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDelNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDelNameFocusLost(evt);
            }
        });
        jPanel1.add(txtDelName);
        txtDelName.setBounds(70, 150, 340, 30);

        jLabel2.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Delete Through Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 110, 200, 40);

        txtDelNumber.setBackground(new java.awt.Color(204, 255, 204));
        txtDelNumber.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        txtDelNumber.setForeground(new java.awt.Color(153, 153, 153));
        txtDelNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDelNumber.setText("Number");
        txtDelNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtDelNumber.setMaximumSize(new java.awt.Dimension(4, 27));
        txtDelNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDelNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDelNumberFocusLost(evt);
            }
        });
        txtDelNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDelNumberKeyTyped(evt);
            }
        });
        jPanel1.add(txtDelNumber);
        txtDelNumber.setBounds(70, 290, 340, 30);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Delete Through Number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 250, 200, 40);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("OR");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(210, 210, 30, 40);

        lblDeleteMessage.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        lblDeleteMessage.setForeground(new java.awt.Color(204, 255, 204));
        lblDeleteMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDeleteMessage);
        lblDeleteMessage.setBounds(215, 390, 190, 20);

        btnDeleteName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (5).png"))); // NOI18N
        btnDeleteName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteNameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteNameMouseReleased(evt);
            }
        });
        jPanel1.add(btnDeleteName);
        btnDeleteName.setBounds(300, 180, 104, 50);

        btnDeleteNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (5).png"))); // NOI18N
        btnDeleteNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteNumberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteNumberMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDeleteNumberMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDeleteNumberMouseReleased(evt);
            }
        });
        jPanel1.add(btnDeleteNumber);
        btnDeleteNumber.setBounds(300, 320, 104, 50);

        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(500, 300, 100, 100);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Home");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(500, 390, 100, 30);

        bg_walpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_walpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wooden-wall-1308152_1280.jpg"))); // NOI18N
        jPanel1.add(bg_walpaper);
        bg_walpaper.setBounds(0, 0, 600, 423);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtDelNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDelNumberKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_txtDelNumberKeyTyped

    private void txtDelNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDelNameFocusGained
        // TODO add your handling code here:
        if (txtDelName.getText().equals("Name")){
            txtDelName.setText("");
        }
        txtDelName.setForeground(Color.black);
    }//GEN-LAST:event_txtDelNameFocusGained

    private void txtDelNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDelNameFocusLost
        // TODO add your handling code here:
        if (txtDelName.getText().equals("")){
            txtDelName.setText("Name");
        }
        if (txtDelName.getText().equals("Name")){
        //         [153,153,153]
            txtDelName.setForeground(new Color(153,153,153));
        
        }
        else{
            txtDelName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtDelNameFocusLost

    private void txtDelNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDelNumberFocusGained
        // TODO add your handling code here:
        if (txtDelNumber.getText().equals("Number")){
            txtDelNumber.setText("");
        }
        txtDelNumber.setForeground(Color.black);
    }//GEN-LAST:event_txtDelNumberFocusGained

    private void txtDelNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDelNumberFocusLost
        // TODO add your handling code here:
        if (txtDelNumber.getText().equals("")){
            txtDelNumber.setText("Number");
        }
        
        if (txtDelNumber.getText().equals("Number")){
        //         [153,153,153]
            txtDelNumber.setForeground(new Color(153,153,153));
        }
        else{
            txtDelNumber.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtDelNumberFocusLost

    private void btnDeleteNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNameMouseEntered
        // TODO add your handling code here:
        btnDeleteName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (6).png")));
    }//GEN-LAST:event_btnDeleteNameMouseEntered

    private void btnDeleteNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNameMouseExited
        // TODO add your handling code here:
        btnDeleteName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (5).png")));
    }//GEN-LAST:event_btnDeleteNameMouseExited

    private void btnDeleteNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNameMousePressed
        // TODO add your handling code here:
        btnDeleteName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (7).png")));
    }//GEN-LAST:event_btnDeleteNameMousePressed

    private void btnDeleteNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNameMouseReleased
        // TODO add your handling code here:
        btnDeleteName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (5).png")));
        if (txtDelName.getText().equals("") || txtDelName.getText().equals("Name")){
            lblDeleteMessage.setText("Please Enter Name");
        }
        
        else{  
        String uContactName = txtDelName.getText();
	String dbName = "jdbc:mysql://localhost/DBPhoneBook";
	String dbUser = "root";
	String dbPass = "root";
        int response =  JOptionPane.showConfirmDialog(this, "Are Sure Want to Delete This Contact ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
    switch (response) {
        case JOptionPane.YES_OPTION: {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(dbName, dbUser, "");
                Statement st = con.createStatement();
                st.executeUpdate("DELETE FROM tab_Contact WHERE uName = '"+uContactName+"'");
                lblDeleteMessage.setText("Contact Deleted Successfully");
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.print(ex);
        }       break;
			
        }
            case JOptionPane.NO_OPTION: {
                lblDeleteMessage.setText("Contact Deletion Unsuccessfull");
                break;
            }
            case JOptionPane.CLOSED_OPTION: {
                lblDeleteMessage.setText("Contact Deletion Unsuccessfull");
                break;
            }
            default: {
                break;
            }
	}
        }
        txtDelName.setText("");
    }//GEN-LAST:event_btnDeleteNameMouseReleased

    
    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48 (1).png")));
    }//GEN-LAST:event_btnExitMousePressed

    
    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png")));
        this.dispose();
    }//GEN-LAST:event_btnExitMouseReleased

    private void btnDeleteNumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNumberMouseEntered
        // TODO add your handling code here:
        btnDeleteNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (6).png")));
    }//GEN-LAST:event_btnDeleteNumberMouseEntered

    private void btnDeleteNumberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNumberMouseExited
        // TODO add your handling code here:
        btnDeleteNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (5).png")));
    }//GEN-LAST:event_btnDeleteNumberMouseExited

    private void btnDeleteNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNumberMousePressed
        // TODO add your handling code here:
        btnDeleteNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (7).png")));
    }//GEN-LAST:event_btnDeleteNumberMousePressed

    private void btnDeleteNumberMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteNumberMouseReleased
        // TODO add your handling code here:
        btnDeleteNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (5).png")));
        if (txtDelName.getText().equals("") || txtDelName.getText().equals("Number")){
            lblDeleteMessage.setText("Please Enter Number");
        }
        
        else{  
        String uContactNum = txtDelNumber.getText();
	String dbName = "jdbc:mysql://localhost/DBPhoneBook";
	String dbUser = "root";
	String dbPass = "root";
        int response =  JOptionPane.showConfirmDialog(this, "Are Sure Want to Delete This Contact ?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       
    switch (response) {
        case JOptionPane.YES_OPTION: {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con = DriverManager.getConnection(dbName, dbUser, "");
                Statement st = con.createStatement();
                st.executeUpdate("DELETE FROM tab_Contact WHERE uContact = '"+uContactNum+"'");
                lblDeleteMessage.setText("Contact Deleted Successfully");
            } catch (ClassNotFoundException | SQLException ex) {
                System.out.print(ex);
        }       break;
			
        }
            case JOptionPane.NO_OPTION: {
                lblDeleteMessage.setText("Contact Deletion Unsuccessfull");
                break;
            }
            case JOptionPane.CLOSED_OPTION: {
                lblDeleteMessage.setText("Contact Deletion Unsuccessfull");
                break;
            }
            default: {
                break;
            }
	}
        }
        txtDelNumber.setText("");
    }//GEN-LAST:event_btnDeleteNumberMouseReleased

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (1).png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (2).png")));
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
        new MainFram().setVisible(true);
        new DeleteContact().setVisible(false);
    }//GEN-LAST:event_btnHomeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteContact().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_walpaper;
    private javax.swing.JLabel btnDeleteName;
    private javax.swing.JLabel btnDeleteNumber;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeleteMessage;
    private javax.swing.JTextField txtDelName;
    private javax.swing.JTextField txtDelNumber;
    // End of variables declaration//GEN-END:variables
}
