/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author M.K
 */
public class FindContact extends javax.swing.JFrame {

    /**
     * Creates new form FindContact
     */
    public FindContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblFindWithName = new javax.swing.JLabel();
        txtFindName = new javax.swing.JTextField();
        btnFindName = new javax.swing.JLabel();
        lblFindWithNumber = new javax.swing.JLabel();
        txtFindNumber = new javax.swing.JTextField();
        btnFindNumber = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblUserContact = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg_wallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 423));
        setMinimumSize(new java.awt.Dimension(600, 423));

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 423));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 423));
        jPanel1.setLayout(null);

        lblTitle.setFont(new java.awt.Font("Arial Unicode MS", 1, 25)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Find Contacts");
        lblTitle.setMaximumSize(new java.awt.Dimension(386, 34));
        lblTitle.setMinimumSize(new java.awt.Dimension(386, 34));
        lblTitle.setPreferredSize(new java.awt.Dimension(386, 34));
        jPanel1.add(lblTitle);
        lblTitle.setBounds(0, 30, 600, 50);

        lblFindWithName.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        lblFindWithName.setForeground(new java.awt.Color(255, 255, 255));
        lblFindWithName.setText("Find Through Name");
        jPanel1.add(lblFindWithName);
        lblFindWithName.setBounds(70, 110, 200, 40);

        txtFindName.setBackground(new java.awt.Color(204, 255, 255));
        txtFindName.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        txtFindName.setForeground(new java.awt.Color(153, 153, 153));
        txtFindName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFindName.setText("Name");
        txtFindName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFindName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFindNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFindNameFocusLost(evt);
            }
        });
        jPanel1.add(txtFindName);
        txtFindName.setBounds(70, 150, 340, 30);

        btnFindName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFindName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (11).png"))); // NOI18N
        btnFindName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFindNameMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFindNameMouseReleased(evt);
            }
        });
        jPanel1.add(btnFindName);
        btnFindName.setBounds(470, 140, 84, 50);

        lblFindWithNumber.setFont(new java.awt.Font("Arial Unicode MS", 1, 16)); // NOI18N
        lblFindWithNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblFindWithNumber.setText("Find Through Number");
        jPanel1.add(lblFindWithNumber);
        lblFindWithNumber.setBounds(70, 210, 200, 40);

        txtFindNumber.setBackground(new java.awt.Color(204, 255, 255));
        txtFindNumber.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        txtFindNumber.setForeground(new java.awt.Color(153, 153, 153));
        txtFindNumber.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFindNumber.setText("Number");
        txtFindNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFindNumber.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtFindNumberFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtFindNumberFocusLost(evt);
            }
        });
        txtFindNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFindNumberKeyTyped(evt);
            }
        });
        jPanel1.add(txtFindNumber);
        txtFindNumber.setBounds(70, 250, 340, 30);

        btnFindNumber.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnFindNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (11).png"))); // NOI18N
        btnFindNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnFindNumberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnFindNumberMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFindNumberMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFindNumberMouseReleased(evt);
            }
        });
        jPanel1.add(btnFindNumber);
        btnFindNumber.setBounds(470, 240, 84, 50);

        lblUserName.setFont(new java.awt.Font("Arial Unicode MS", 3, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(255, 255, 255));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserName.setText("Name: ");
        jPanel1.add(lblUserName);
        lblUserName.setBounds(70, 320, 340, 20);

        lblUserContact.setFont(new java.awt.Font("Arial Unicode MS", 3, 14)); // NOI18N
        lblUserContact.setForeground(new java.awt.Color(255, 255, 255));
        lblUserContact.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserContact.setText("Contact No.: ");
        jPanel1.add(lblUserContact);
        lblUserContact.setBounds(70, 350, 340, 20);

        lblUserEmail.setFont(new java.awt.Font("Arial Unicode MS", 3, 14)); // NOI18N
        lblUserEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblUserEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUserEmail.setText("Email ID:");
        jPanel1.add(lblUserEmail);
        lblUserEmail.setBounds(70, 380, 340, 20);

        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(500, 300, 100, 100);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(500, 390, 100, 30);

        bg_wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wooden-wall-1308152_1280.jpg"))); // NOI18N
        jPanel1.add(bg_wallpaper);
        bg_wallpaper.setBounds(0, 0, 600, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFindNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNameMouseEntered
        // TODO add your handling code here:
        btnFindName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (12).png")));
    }//GEN-LAST:event_btnFindNameMouseEntered

    private void btnFindNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNameMouseExited
        // TODO add your handling code here:
        btnFindName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (11).png")));
    }//GEN-LAST:event_btnFindNameMouseExited

    private void btnFindNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNameMousePressed
        // TODO add your handling code here:
        btnFindName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (13).png")));
    }//GEN-LAST:event_btnFindNameMousePressed

    private void btnFindNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNameMouseReleased
        // TODO add your handling code here:
        btnFindName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (11).png")));
        
        // Find contact details with Name
        
        String userName = txtFindName.getText();
        String dbName = "jdbc:mysql://localhost/DBPhoneBook";
        String dbUser = "root";
        String dbPass = "root";
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;   
        try{
            String sql= "SELECT uName, uContact, uEmail FROM tab_Contact WHERE uName = '"+userName+"'";
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection (dbName,dbUser,"");
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            while(rs.next()){
                String uName = rs.getString("uName");
                String uContact = rs.getString("uContact");
                String uEmail = rs.getString("uEmail");
                lblUserName.setText("Name: " + uName);
//                System.out.print(uName + "\n");
                lblUserContact.setText("Contact No.: " + uContact);
//                System.out.print(uContact + "\n");
                lblUserEmail.setText("Email: " + uEmail);
//                System.out.print(uEmail + "\n\n");
            }
            
        }
        catch(ClassNotFoundException | SQLException e){
            System.out.print(e);
        }
    
    }//GEN-LAST:event_btnFindNameMouseReleased

    private void txtFindNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFindNameFocusGained
        // TODO add your handling code here:
        if (txtFindName.getText().equals("Name")){
            txtFindName.setText("");
        }
        txtFindName.setForeground(Color.black);
    }//GEN-LAST:event_txtFindNameFocusGained

    private void txtFindNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFindNameFocusLost
        // TODO add your handling code here:
        if (txtFindName.getText().equals("")){
            txtFindName.setText("Name");
        }
        //         [153,153,153]
        if(txtFindName.getText().equals("Name")){
            txtFindName.setForeground(new Color(153,153,153));
        }
        else{
            txtFindName.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFindNameFocusLost

    private void btnFindNumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNumberMouseEntered
        // TODO add your handling code here:
        btnFindNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (12).png")));
    }//GEN-LAST:event_btnFindNumberMouseEntered

    private void btnFindNumberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNumberMouseExited
        // TODO add your handling code here:
        btnFindNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (11).png")));
    }//GEN-LAST:event_btnFindNumberMouseExited

    private void btnFindNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNumberMousePressed
        // TODO add your handling code here:
        btnFindNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (13).png")));
    }//GEN-LAST:event_btnFindNumberMousePressed

    private void btnFindNumberMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFindNumberMouseReleased
        // TODO add your handling code here:
        btnFindNumber.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (11).png")));
        // Find Contact With Number
        
        String userNumber = txtFindNumber.getText();
        String dbName = "jdbc:mysql://localhost/DBPhoneBook";
        String dbUser = "root";
        String dbPass = "root";
        Connection conn = null;
        Statement st = null;
        ResultSet rs = null;
        try{
            String sql= "SELECT uName, uContact, uEmail FROM tab_Contact WHERE uContact = '"+userNumber+"'";
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = DriverManager.getConnection (dbName,dbUser,"");
            st = conn.createStatement();
            rs = st.executeQuery(sql);

            while(rs.next()){
                String uName = rs.getString("uName");
                String uContact = rs.getString("uContact");
                String uEmail = rs.getString("uEmail");
                lblUserName.setText("Name: " + uName);
                //                System.out.print(uName + "\n");
                lblUserContact.setText("Contact No.: " + uContact);
                //                System.out.print(uContact + "\n");
                lblUserEmail.setText("Email: " + uEmail);
                //                System.out.print(uEmail + "\n\n");
            }

        }
        catch(ClassNotFoundException | SQLException e){
            System.out.print(e);
        }

    }//GEN-LAST:event_btnFindNumberMouseReleased

    private void txtFindNumberFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFindNumberFocusGained
        // TODO add your handling code here:
        if (txtFindNumber.getText().equals("Number")){
            txtFindNumber.setText("");
        }
        txtFindNumber.setForeground(Color.black);
    }//GEN-LAST:event_txtFindNumberFocusGained

    private void txtFindNumberFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtFindNumberFocusLost
        // TODO add your handling code here:
        if (txtFindNumber.getText().equals("")){
            txtFindNumber.setText("Number");
        }
        //         [153,153,153]
        if(txtFindNumber.getText().equals("Number")){
            txtFindNumber.setForeground(new Color(153,153,153));
        }
        else{
            txtFindNumber.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtFindNumberFocusLost

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
         btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (1).png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
         btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
         btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (2).png")));
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        // TODO add your handling code here:
         btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
         new MainFram().setVisible(true);
         new FindContact().setVisible(false);
    }//GEN-LAST:event_btnHomeMouseReleased

    private void txtFindNumberKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFindNumberKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_txtFindNumberKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_wallpaper;
    private javax.swing.JLabel btnFindName;
    private javax.swing.JLabel btnFindNumber;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFindWithName;
    private javax.swing.JLabel lblFindWithNumber;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUserContact;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField txtFindName;
    private javax.swing.JTextField txtFindNumber;
    // End of variables declaration//GEN-END:variables
}
