/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phonebook;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.SwingUtilities;

/**
 *
 * @author M.K
 */
public class NewContact extends javax.swing.JFrame {

    /**
     * Creates new form NewContact
     */
    public NewContact() {
        initComponents();
        jPanel1.setFocusable(true);
        btnExit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        img_contact = new javax.swing.JLabel();
        txtNewName = new javax.swing.JTextField();
        txtNewContact = new javax.swing.JTextField();
        txtNewEmail = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg_wallpaper = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 423));
        setMinimumSize(new java.awt.Dimension(600, 423));

        jPanel1.setMaximumSize(new java.awt.Dimension(600, 423));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 423));
        jPanel1.setLayout(null);

        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnExitMouseReleased(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(540, 20, 40, 40);

        jLabel3.setFont(new java.awt.Font("Arial Unicode MS", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add New Contact in Phonebook");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 30, 600, 50);

        img_contact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        img_contact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-name-100.png"))); // NOI18N
        jPanel1.add(img_contact);
        img_contact.setBounds(130, 90, 100, 110);

        txtNewName.setBackground(new java.awt.Color(203, 255, 203));
        txtNewName.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        txtNewName.setForeground(new java.awt.Color(153, 153, 153));
        txtNewName.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNewName.setText("Name");
        txtNewName.setToolTipText("");
        txtNewName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNewName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNewName.setMaximumSize(new java.awt.Dimension(4, 27));
        txtNewName.setName(""); // NOI18N
        txtNewName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewNameFocusLost(evt);
            }
        });
        txtNewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtNewName);
        txtNewName.setBounds(150, 210, 300, 25);

        txtNewContact.setBackground(new java.awt.Color(204, 255, 204));
        txtNewContact.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        txtNewContact.setForeground(new java.awt.Color(153, 153, 153));
        txtNewContact.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNewContact.setText("Contact No.");
        txtNewContact.setToolTipText("");
        txtNewContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNewContact.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNewContact.setMaximumSize(new java.awt.Dimension(4, 27));
        txtNewContact.setName(""); // NOI18N
        txtNewContact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewContactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewContactFocusLost(evt);
            }
        });
        txtNewContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewContactActionPerformed(evt);
            }
        });
        txtNewContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNewContactKeyTyped(evt);
            }
        });
        jPanel1.add(txtNewContact);
        txtNewContact.setBounds(150, 250, 300, 25);

        txtNewEmail.setBackground(new java.awt.Color(204, 255, 204));
        txtNewEmail.setFont(new java.awt.Font("Arial Unicode MS", 0, 16)); // NOI18N
        txtNewEmail.setForeground(new java.awt.Color(153, 153, 153));
        txtNewEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNewEmail.setText("Email ID");
        txtNewEmail.setToolTipText("");
        txtNewEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNewEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNewEmail.setMaximumSize(new java.awt.Dimension(4, 27));
        txtNewEmail.setName(""); // NOI18N
        txtNewEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNewEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNewEmailFocusLost(evt);
            }
        });
        txtNewEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtNewEmail);
        txtNewEmail.setBounds(150, 290, 300, 25);

        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (2).png"))); // NOI18N
        btnSubmit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSubmitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSubmitMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSubmitMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSubmitMouseReleased(evt);
            }
        });
        jPanel1.add(btnSubmit);
        btnSubmit.setBounds(370, 330, 80, 40);

        lblMessage.setFont(new java.awt.Font("Arial Unicode MS", 2, 12)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(204, 255, 204));
        jPanel1.add(lblMessage);
        lblMessage.setBounds(215, 390, 190, 20);

        btnHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png"))); // NOI18N
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHomeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHomeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHomeMouseReleased(evt);
            }
        });
        jPanel1.add(btnHome);
        btnHome.setBounds(0, 300, 110, 100);

        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 390, 110, 30);

        bg_wallpaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg_wallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wooden-wall-1308152_1280.jpg"))); // NOI18N
        jPanel1.add(bg_wallpaper);
        bg_wallpaper.setBounds(0, 0, 600, 420);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewNameActionPerformed

    private void txtNewContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewContactActionPerformed

    private void txtNewEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewEmailActionPerformed

    private void btnSubmitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseEntered
        // TODO add your handling code here:
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (3).png")));
    }//GEN-LAST:event_btnSubmitMouseEntered

    private void btnSubmitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseExited
        // TODO add your handling code here:
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (2).png")));
    }//GEN-LAST:event_btnSubmitMouseExited

    private void btnSubmitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMousePressed
        // TODO add your handling code here:
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (4).png")));
    }//GEN-LAST:event_btnSubmitMousePressed

    private void btnSubmitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSubmitMouseReleased
        // TODO add your handling code here:
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button (2).png")));
        String uName = txtNewName.getText();
        String uContact = txtNewContact.getText();
        String uEmail = txtNewEmail.getText();
        String dbName = "jdbc:mysql://localhost/DBPhoneBook";
        String dbUser = "root";
        String dbPass = "root";
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con =  DriverManager.getConnection(dbName, dbUser, "");
            Statement st = con.createStatement();
            st.executeUpdate("INSERT INTO tab_Contact (uName, uContact, uEmail) VALUES ('"+uName+"', '"+uContact+"', '"+uEmail+"')");
            lblMessage.setText("Contact Add Successfully");
        } catch (ClassNotFoundException | SQLException ex) {
                System.out.print(ex);
        }
        
        txtNewName.setText("");
        txtNewContact.setText("");
        txtNewEmail.setText("");
    }                                         

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        new MainFram().setVisible(true);
    }//GEN-LAST:event_btnSubmitMouseReleased

    private void txtNewNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewNameFocusGained
        // TODO add your handling code here:
        if (txtNewName.getText().equals("Name")){
            txtNewName.setText("");
        }
        txtNewName.setForeground(Color.black);
    }//GEN-LAST:event_txtNewNameFocusGained

    private void txtNewNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewNameFocusLost
        // TODO add your handling code here:
        if (txtNewName.getText().equals("")){
            txtNewName.setText("Name");
        }
        if (txtNewName.getText().equals("Name")){
//         [153,153,153]
            txtNewName.setForeground(new Color(153,153,153));
        }
        else{
            txtNewName.setForeground(Color.black);
        }
         
    }//GEN-LAST:event_txtNewNameFocusLost

    private void txtNewContactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewContactFocusGained
        // TODO add your handling code here:
        if (txtNewContact.getText().equals("Contact No.")){
            txtNewContact.setText("");
        }
        txtNewContact.setForeground(Color.black);
    }//GEN-LAST:event_txtNewContactFocusGained

    private void txtNewContactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewContactFocusLost
        // TODO add your handling code here:
        if (txtNewContact.getText().equals("")){
            txtNewContact.setText("Contact No.");
        }
        if (txtNewContact.getText().equals("Contact No.")){
        //         [153,153,153]
            txtNewContact.setForeground(new Color(153,153,153));
        }
        else{
            txtNewContact.setForeground(Color.black);
        }
    }//GEN-LAST:event_txtNewContactFocusLost

    private void txtNewEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewEmailFocusGained
        // TODO add your handling code here:
        if (txtNewEmail.getText().equals("Email ID")){
            txtNewEmail.setText("");
        }
        txtNewEmail.setForeground(Color.black);
    }//GEN-LAST:event_txtNewEmailFocusGained

    private void txtNewEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNewEmailFocusLost
        // TODO add your handling code here:
        if (txtNewEmail.getText().equals("")){
            txtNewEmail.setText("Email ID");
        }
        if (txtNewEmail.getText().equals("Email ID")){
        //         [153,153,153]
            txtNewEmail.setForeground(new Color(153,153,153));
        }
        else{
            txtNewEmail.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_txtNewEmailFocusLost

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jLabel3MousePressed

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48 (1).png")));
    }//GEN-LAST:event_btnExitMousePressed

    private void btnExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseReleased
        // TODO add your handling code here:
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-close-window-48.png")));
        this.dispose();
//        new MainFram().dispose();
    }//GEN-LAST:event_btnExitMouseReleased

    private void txtNewContactKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewContactKeyTyped
        // TODO add your handling code here:
        
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||(c==KeyEvent.VK_DELETE))){
            evt.consume();
        }
    }//GEN-LAST:event_txtNewContactKeyTyped

    private void btnHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseEntered
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (1).png")));
    }//GEN-LAST:event_btnHomeMouseEntered

    private void btnHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseExited
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
    }//GEN-LAST:event_btnHomeMouseExited

    private void btnHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMousePressed
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100 (2).png")));
    }//GEN-LAST:event_btnHomeMousePressed

    private void btnHomeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseReleased
        // TODO add your handling code here:
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-100.png")));
        new MainFram().setVisible(true);
        new NewContact().setVisible(false);
    }//GEN-LAST:event_btnHomeMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewContact.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewContact().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_wallpaper;
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnSubmit;
    private javax.swing.JLabel img_contact;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTextField txtNewContact;
    private javax.swing.JTextField txtNewEmail;
    private javax.swing.JTextField txtNewName;
    // End of variables declaration//GEN-END:variables
}
